const fs = require('fs');

const slTrans = {
  library: "Knjižnica",
  searchPlaceholder: "Iskanje knjige...",
  sortByDate: "Datum dodajanja",
  sortByTitle: "Naslov",
  sortByAuthor: "Avtor",
  sortByRating: "Ocena",
  sortByProgress: "Napredek",
  addBook: "Dodaj knjigo",
  editBook: "Uredi",
  deleteBook: "Izbriši",
  saveBook: "Shrani",
  cancel: "Prekliči",
  add: "Dodaj",
  title: "Naslov",
  author: "Avtor",
  isbn: "ISBN",
  status: "Stanje",
  pages: "Strani",
  statusToRead: "Za branje",
  statusReading: "Trenutno berem",
  statusRead: "Prebrano",
  rating: "Ocena",
  notes: "Opombe",
  coverImage: "Slika naslovnice (URL ali base64)",
  pageUpdate: "Posodobi stran",
  read: "Prebrano",
  pagesAbbr: "str.",
  tabShelf: "Knjižna polica",
  tabToRead: "Za branje",
  tabReading: "Berem",
  tabRead: "Prebrano",
  tabStats: "Statistika",
  emptyShelfTitle: "Vaša knjižna polica je prazna",
  emptyShelfDesc: "Dodajte knjige preko seznama 'Za branje' ali s klikom na gumb Dodaj zgoraj.",
  emptyToReadTitle: "Vaš seznam za branje je prazen",
  emptyToReadDesc: "Ste našli zanimivo knjigo? Dodajte jo in začnite brati!",
  emptyReadingTitle: "Trenutno ne berete nobene knjige",
  emptyReadingDesc: "Začnite brati knjigo s seznama 'Za branje' ali dodajte novo knjigo v stanje 'Trenutno berem'.",
  emptyReadTitle: "Niste še prebrali nobene knjige",
  emptyReadDesc: "Vsaka prebrana knjiga je pomembna. Dokončajte knjigo in jo premaknite sem.",
  confirmDeleteTitle: "Izbriši knjigo",
  confirmDeleteDesc: "Ste prepričani, da želite izbrisati to knjigo? Tega dejanja ni mogoče razveljaviti.",
  statistics: "Statistika branja",
  totalBooks: "Skupno knjig",
  booksRead: "Prebranih knjig",
  totalPages: "Prebranih strani",
  averageRating: "Povprečna ocena",
  monthlyProgress: "Mesečni napredek",
  pagesReadThisMonth: "Prebranih strani ta mesec",
  booksFinishedThisMonth: "Knjig končanih ta mesec",
  booksFinishedMonthlyPattern: "Skupno knjig, končanih skozi leto",
  booksByAppStatus: "Knjige po statusu aplikacije",
  months: "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Avg,Sep,Okt,Nov,Dec",
  monthsFull: "Januar,Februar,Marec,April,Maj,Junij,Julij,Avgust,September,Oktober,November,December",
  settings: "Nastavitve",
  settingsAppearance: "Videz",
  settingsData: "Podatki",
  language: "Jezik",
  theme: "Tema",
  themeLight: "Svetla",
  themeDark: "Temna",
  themeSystem: "Sistemska",
  colorTheme: "Barvna shema",
  exportData: "Izvozi podatke",
  importData: "Uvozi podatke",
  exportDesc: "Prenesite vse svoje knjige kot JSON datoteko.",
  importDesc: "Obnovite svoje knjige iz JSON datoteki.",
  importSuccess: "Uspešno uvoženih knjig: ",
  importFormatError: "Neveljaven format datoteke.",
  importError: "Napaka pri prenosu podatkov.",
  version: "Različica",
  privacyPolicy: "Politika Zasebnosti",
  termsOfService: "Pogoji Uporabe"
};

const elTrans = {
  library: "Βιβλιοθήκη",
  searchPlaceholder: "Αναζήτηση βιβλίου...",
  sortByDate: "Ημερομηνία Προσθήκης",
  sortByTitle: "Τίτλος",
  sortByAuthor: "Συγγραφέας",
  sortByRating: "Βαθμολογία",
  sortByProgress: "Πρόοδος",
  addBook: "Προσθήκη Βιβλίου",
  editBook: "Επεξεργασία",
  deleteBook: "Διαγραφή",
  saveBook: "Αποθήκευση",
  cancel: "Ακύρωση",
  add: "Προσθήκη",
  title: "Τίτλος",
  author: "Συγγραφέας",
  isbn: "ISBN",
  status: "Κατάσταση",
  pages: "Σελίδες",
  statusToRead: "Προς Ανάγνωση",
  statusReading: "Διαβάζω Τώρα",
  statusRead: "Διαβάστηκε",
  rating: "Βαθμολογία",
  notes: "Σημειώσεις",
  coverImage: "Εξώφυλλο (URL ή base64)",
  pageUpdate: "Ενημέρωση σελίδας",
  read: "Διαβάστηκε",
  pagesAbbr: "σελ.",
  tabShelf: "Ράφι",
  tabToRead: "Προς Ανάγνωση",
  tabReading: "Διαβάζω",
  tabRead: "Διαβάστηκε",
  tabStats: "Στατιστικά",
  emptyShelfTitle: "Το ράφι σας είναι άδειο",
  emptyShelfDesc: "Προσθέστε βιβλία μέσω της λίστας 'Προς Ανάγνωση' ή πατώντας Προσθήκη.",
  emptyToReadTitle: "Η λίστα ανάγνωσης είναι άδεια",
  emptyToReadDesc: "Βρήκατε κάποιο ενδιαφέρον βιβλίο; Προσθέστε το!",
  emptyReadingTitle: "Δεν διαβάζετε κανένα βιβλίο τώρα",
  emptyReadingDesc: "Ξεκινήστε ένα βιβλίο από τη λίστα 'Προς Ανάγνωση'.",
  emptyReadTitle: "Δεν έχετε διαβάσει κανένα βιβλίο",
  emptyReadDesc: "Κάθε βιβλίο μετράει. Ολοκληρώστε ένα και μετακινήστε το εδώ.",
  confirmDeleteTitle: "Διαγραφή Βιβλίου",
  confirmDeleteDesc: "Είστε σίγουροι; Αυτή η ενέργεια δεν αναιρείται.",
  statistics: "Στατιστικά",
  totalBooks: "Σύνολο Βιβλίων",
  booksRead: "Βιβλία που Διαβάστηκαν",
  totalPages: "Σελίδες που Διαβάστηκαν",
  averageRating: "Μέση Βαθμολογία",
  monthlyProgress: "Μηνιαία Πρόοδος",
  pagesReadThisMonth: "Σελίδες αυτόν τον μήνα",
  booksFinishedThisMonth: "Βιβλία αυτόν τον μήνα",
  booksFinishedMonthlyPattern: "Βιβλία ανά μήνα",
  booksByAppStatus: "Βιβλία ανά Κατάσταση",
  months: "Ιαν,Φεβ,Μαρ,Απρ,Μαϊ,Ιουν,Ιουλ,Αυγ,Σεπ,Οκτ,Νοε,Δεκ",
  monthsFull: "Ιανουάριος,Φεβρουάριος,Μάρτιος,Απρίλιος,Μάιος,Ιούνιος,Ιούλιος,Αύγουστος,Σεπτέμβριος,Οκτώβριος,Νοέμβριος,Δεκέμβριος",
  settings: "Ρυθμίσεις",
  settingsAppearance: "Εμφάνιση",
  settingsData: "Δεδομένα",
  language: "Γλώσσα",
  theme: "Θέμα",
  themeLight: "Φωτεινό",
  themeDark: "Σκοτεινό",
  themeSystem: "Σύστημα",
  colorTheme: "Χρώμα Θέματος",
  exportData: "Εξαγωγή Δεδομένων",
  importData: "Εισαγωγή Δεδομένων",
  exportDesc: "Λήψη βιβλίων (JSON).",
  importDesc: "Επαναφορά βιβλίων (JSON).",
  importSuccess: "Επιτυχής εισαγωγή: ",
  importFormatError: "Μη έγκυρη μορφή.",
  importError: "Σφάλμα ανάγνωσης.",
  version: "Έκδοση",
  privacyPolicy: "Πολιτική Απορρήτου",
  termsOfService: "Όροι Χρήσης"
};

let i18nPath = 'src/lib/i18n.ts';
let content = fs.readFileSync(i18nPath, 'utf8');

function addLang(lang, json) {
  let jsonStr = JSON.stringify(json, null, 4).replace(/"([^"]+)":/g, '$1:');
  let langStr = `\n  ${lang}: ${jsonStr},`;
  let parts = content.split('};\n\nexport const getTranslation');
  if (parts.length === 2) {
      content = parts[0] + langStr + '\n};\n\nexport const getTranslation' + parts[1];
  }
}

addLang('sl', slTrans);
addLang('el', elTrans);

fs.writeFileSync(i18nPath, content);
