import fs from 'fs';

const slComplete = {
    library: "Knjižnica",
    searchPlaceholder: "Išči knjigo...",
    sortByDate: "Datum dodajanja",
    sortByTitle: "Naslov",
    sortByAuthor: "Avtor",
    sortByRating: "Ocena",
    tabShelf: "Knjižna polica",
    tabToRead: "Za branje",
    tabReading: "Trenutno berem",
    tabRead: "Prebrano",
    tabStats: "Statistika",
    addBook: "Nova knjiga",
    editBook: "Uredi knjigo",
    save: "Shrani",
    title: "Naslov",
    titlePlaceholder: "Npr. Gospodar prstanov",
    author: "Avtor",
    authorPlaceholder: "Npr. J.R.R. Tolkien",
    pages: "Strani",
    status: "Status",
    statusToRead: "Za branje",
    statusReading: "Trenutno berem",
    statusRead: "Prebrano",
    rating: "Ocena",
    notes: "Opombe",
    notesPlaceholder: "Vaše misli, citati...",
    coverOrBookmark: "Naslovnica / Zaznamek",
    selectFromGallery: "Izberi iz galerije",
    removeCover: "Izbriši",
    settings: "Nastavitve",
    appearance: "Videz",
    theme: "Tema",
    themeSystem: "Sistemska",
    themeLight: "Svetla",
    themeDark: "Temna",
    accentColor: "Poudarjena barva",
    language: "Jezik",
    backup: "Podatki in varnostna kopija",
    exportData: "Izvozi podatke",
    importData: "Uvozi podatke",
    clearData: "Počisti podatke",
    clearDataDesc: "Izbrišite vse knjige in ponastavite aplikacijo",
    confirmClearData: "Ali ste prepričani, da želite izbrisati VSE podatke? Tega ni mogoče razveljaviti!",
    aboutApp: "O aplikaciji",
    version: "Različica",
    whatsNew: "Kaj je novega",
    licenses: "Licence",
    email: "E-pošta",
    sourceCode: "Izvorna koda",
    createIssue: "Ustvari zahtevek",
    thirdPartyLicenses: "Licence tretjih oseb",
    termsConditions: "Pogoji uporabe",
    privacyPolicy: "Pravilnik o zasebnosti",
    close: "Zapri",
    emptyShelfTitle: "Ni knjig",
    emptyShelfDesc: "Kliknite spodnji gumb in dodajte svojo prvo knjigo na ta seznam.",
    deleteConfirm: "Ali ste prepričani, da želite izbrisati to knjigo?",
    statsTitle: "Statistika branja",
    thisYear: "Letos",
    totalBooks: "Skupaj knjig",
    booksRead: "Prebranih knjig",
    booksAdded: "Dodanih knjig",
    pagesRead: "Prebranih strani",
    timeSpent: "Porabljen čas",
    streakDays: "Niz (dni)",
    readingProgress: "Napredek branja",
    overview: "Pregled",
    books: "Knjige",
    time: "Čas",
    currentlyReading: "Trenutno berete",
    toRead: "Za branje",
    averageRating: "Povprečna ocena",
    quickView: "Hitri ogled",
    updateProgress: "Posodobi napredek",
    page: "Stran",
    of: "od",
    addNote: "Dodaj opombo",
    startReading: "Začni brati",
    stopReading: "Ustavi časovnik",
    readingSession: "Bralna seja",
    pagesReadCount: "Prebranih strani",
    saveSession: "Shrani sejo",
    cancel: "Prekliči",
    added: "Dodano",
    inThisMonth: "V tem mesecu",
    activityMonths: "Aktivnost v zadnjih mesecih",
    statusDistribution: "Porazdelitev po statusu",
    emptyStatsTitle: "Ni podatkov",
    emptyStatsDesc: "Dodajte knjige, da vidite svojo statistiko knjižnice.",
    selectBook: "Izberite knjigo...",
    whatBookReading: "Katero knjigo ste brali?",
    whatPageFinished: "Na kateri strani ste končali?",
    lastSavedPage: "Zadnja shranjena stran:",
    saveProgress: "Shrani napredek",
    addBookFirst: "Nimate knjig s statusom 'Za branje' ali 'Trenutno berem'. Najprej dodajte knjigo.",
    updateProgressMessage: "Branje končano",
    readingTimeTitle: "Čas za branje?",
    readingTimeDescReading: "Potopite se v zgodbo...",
    readingTimeDescIdle: "Sprostite se in začnite brati. Merite čas in spremljajte napredek.",
    importSuccess: "Uspešno naloženih knjig: ",
    importFormatError: "Neveljaven format datoteke za varnostno kopijo.",
    importError: "Branje datoteke ni uspelo. Prepričajte se, da gre za veljaven varnostni JSON.",
    onGithub: "Na Githubu",
    mitLicense: "MIT licenca"
};

const elComplete = {
    library: "Βιβλιοθήκη",
    searchPlaceholder: "Αναζήτηση βιβλίου...",
    sortByDate: "Ημερομηνία Προσθήκης",
    sortByTitle: "Τίτλος",
    sortByAuthor: "Συγγραφέας",
    sortByRating: "Βαθμολογία",
    tabShelf: "Ράφι",
    tabToRead: "Προς Ανάγνωση",
    tabReading: "Διαβάζω",
    tabRead: "Διαβάστηκε",
    tabStats: "Στατιστικά",
    addBook: "Νέο Βιβλίο",
    editBook: "Επεξεργασία Βιβλίου",
    save: "Αποθήκευση",
    title: "Τίτλος",
    titlePlaceholder: "Π.χ. Ο Άρχοντας των Δαχτυλιδιών",
    author: "Συγγραφέας",
    authorPlaceholder: "Π.χ. J.R.R. Tolkien",
    pages: "Σελίδες",
    status: "Κατάσταση",
    statusToRead: "Προς Ανάγνωση",
    statusReading: "Διαβάζω Τώρα",
    statusRead: "Διαβάστηκε",
    rating: "Βαθμολογία",
    notes: "Σημειώσεις",
    notesPlaceholder: "Οι σκέψεις σας, αποσπάσματα...",
    coverOrBookmark: "Εξώφυλλο / Σελιδοδείκτης",
    selectFromGallery: "Επιλογή από γκαλερί",
    removeCover: "Διαγραφή",
    settings: "Ρυθμίσεις",
    appearance: "Εμφάνιση",
    theme: "Θέμα",
    themeSystem: "Σύστημα",
    themeLight: "Φωτεινό",
    themeDark: "Σκοτεινό",
    accentColor: "Χρώμα ανάδειξης",
    language: "Γλώσσα",
    backup: "Δεδομένα & αντίγραφα",
    exportData: "Εξαγωγή δεδομένων",
    importData: "Εισαγωγή δεδομένων",
    clearData: "Εκκαθάριση δεδομένων",
    clearDataDesc: "Διαγραφή όλων των βιβλίων και επαναφορά",
    confirmClearData: "Είστε σίγουροι ότι θέλετε να διαγράψετε ΟΛΑ τα δεδομένα; Η ενέργεια δεν αναιρείται!",
    aboutApp: "Σχετικά με την εφαρμογή",
    version: "Έκδοση",
    whatsNew: "Τι νέο υπάρχει",
    licenses: "Άδειες",
    email: "Email",
    sourceCode: "Πηγαίος κώδικας",
    createIssue: "Αναφορά προβλήματος",
    thirdPartyLicenses: "Άδειες τρίτων",
    termsConditions: "Όροι και Προϋποθέσεις",
    privacyPolicy: "Πολιτική Απορρήτου",
    close: "Κλείσιμο",
    emptyShelfTitle: "Κανένα βιβλίο",
    emptyShelfDesc: "Κάντε κλικ στο παρακάτω κουμπί για να προσθέσετε το πρώτο σας βιβλίο.",
    deleteConfirm: "Σίγουρα θέλετε να διαγράψετε αυτό το βιβλίο;",
    statsTitle: "Στατιστικά Ανάγνωσης",
    thisYear: "Φέτος",
    totalBooks: "Σύνολο Βιβλίων",
    booksRead: "Βιβλία που Διαβάστηκαν",
    booksAdded: "Βιβλία που Προστέθηκαν",
    pagesRead: "Σελίδες που Διαβάστηκαν",
    timeSpent: "Χρόνος Ανάγνωσης",
    streakDays: "Σερί (ημέρες)",
    readingProgress: "Πρόοδος Ανάγνωσης",
    overview: "Επισκόπηση",
    books: "Βιβλία",
    time: "Χρόνος",
    currentlyReading: "Διαβάζετε τώρα",
    toRead: "Προς Ανάγνωση",
    averageRating: "Μέση Βαθμολογία",
    quickView: "Γρήγορη προβολή",
    updateProgress: "Ενημέρωση Πρόοδου",
    page: "Σελίδα",
    of: "από",
    addNote: "Προσθήκη Σημείωσης",
    startReading: "Έναρξη",
    stopReading: "Διακοπή χρόνου",
    readingSession: "Συνεδρία Ανάγνωσης",
    pagesReadCount: "Σελίδες που Διαβάστηκαν",
    saveSession: "Αποθήκευση Συνεδρίας",
    cancel: "Ακύρωση",
    added: "Προστέθηκε",
    inThisMonth: "Αυτόν τον μήνα",
    activityMonths: "Δραστηριότητα τους τελευταίους μήνες",
    statusDistribution: "Κατανομή κατάστασης",
    emptyStatsTitle: "Δεν υπάρχουν δεδομένα",
    emptyStatsDesc: "Προσθέστε βιβλία για να δείτε τα στατιστικά σας.",
    selectBook: "Επιλέξτε ένα βιβλίο...",
    whatBookReading: "Ποιο βιβλίο διαβάζατε;",
    whatPageFinished: "Σε ποια σελίδα τελειώσατε;",
    lastSavedPage: "Τελευταία σελίδα:",
    saveProgress: "Αποθήκευση πρόοδου",
    addBookFirst: "Δεν έχετε βιβλία σε κατάσταση 'Προς Ανάγνωση' ή 'Διαβάζω Τώρα'. Αρχικά προσθέστε ένα βιβλίο.",
    updateProgressMessage: "Ολοκλήρωση ανάγνωσης",
    readingTimeTitle: "Ώρα για ανάγνωση;",
    readingTimeDescReading: "Βυθιστείτε στην ιστορία...",
    readingTimeDescIdle: "Χαλαρώστε και ξεκινήστε το διάβασμα. Παρακολουθήστε την ανάγνωση σας.",
    importSuccess: "Επιτυχής φόρτωση βιβλίων: ",
    importFormatError: "Μη έγκυρη μορφή αρχείου.",
    importError: "Σφάλμα ανάγνωσης. Βεβαιωθείτε ότι είναι έγκυρο αρχείο JSON.",
    onGithub: "Στο Github",
    mitLicense: "Άδεια MIT"
};

let i18nPath = 'src/lib/i18n.ts';
let content = fs.readFileSync(i18nPath, 'utf8');

// Replace the existing sl: { ... } and el: { ... } blocks
function replaceLang(lang, jsonObj) {
    let searchStr = `\n  ${lang}: {\n`;
    let startIndex = content.indexOf(searchStr);
    if (startIndex !== -1) {
        // Find the matching closing bracket
        let depth = 0;
        let endIndex = -1;
        for (let i = startIndex + searchStr.length - 2; i < content.length; i++) {
            if (content[i] === '{') depth++;
            if (content[i] === '}') {
                depth--;
                if (depth === 0) {
                    endIndex = i;
                    break;
                }
            }
        }
        
        if (endIndex !== -1) {
            let jsonStr = JSON.stringify(jsonObj, null, 4).replace(/"([^"]+)":/g, '$1:');
            // Check if there is a comma right after the closing bracket
            if (content[endIndex + 1] === ',') {
                endIndex++; 
            }
            content = content.substring(0, startIndex) + `\n  ${lang}: ${jsonStr},` + content.substring(endIndex + 1);
        }
    }
}

replaceLang('sl', slComplete);
replaceLang('el', elComplete);

fs.writeFileSync(i18nPath, content);
