import * as fs from 'fs';

// Read i18n
const i18nPath = './src/lib/i18n.ts';
let i18nContent = fs.readFileSync(i18nPath, 'utf8');

const langs = [
  'fi', 'sv', 'no', 'da', 'nl', 'lb', 'pt', 'it', 'hr', 'sk', 'et', 'lv', 'lt', 'bg', 'tr', 'ko', 'ja', 'is', 'kl'
];

interface Trans {
  [key: string]: Record<string, string>;
}

const translations: Trans = {
  fi: {
    addBook: "Lisää kirja", searchBook: "Etsi kirja...", title: "Otsikko", author: "Kirjailija",
    status: "Tila", toRead: "Luettavaksi", reading: "Luennassa", read: "Luettu",
    save: "Tallenna", cancel: "Peruuta", edit: "Muokkaa", delete: "Poista",
    library: "Biblioteka", myLibrary: "Oma kirjastoni", noBooks: "Kirjoja ei löytynyt.",
    theme: "Teema", language: "Kieli", settings: "Asetukset",
    all: "Kaikki", notes: "Löydökset ja muistiinpanot", coverUrl: "Kannen URL",
    scanBarcode: "Skannaa viivakoodi", cameraPermissionError: "Kameraa ei voitu käyttää. Tarkista luvat.",
    cameraError: "Kameran käynnistyksessä tapahtui virhe.", closeScanner: "Sulje skanneri",
    totalBooks: "Kirjoja yhteensä", pagesRead: "Sivuja luettu", avgRating: "Keskimääräinen arvio",
    stats: "Tilastot", recentBooks: "Viimeisimmät kirjat", emptyStatsDesc: "Lisää kirjoja nähdäksesi kirjastosi tilastot.",
    confirmDelete: "Haluatko varmasti poistaa tämän kirjan?", appearance: "Ulkonäkö",
    dataPrivacy: "Tiedot ja tietosuoja", exportData: "Vie tiedot", importData: "Tuo tiedot",
    about: "Tietoja", sourceCode: "Lähdekoodi", aboutText: "Yksityisyyttä kunnioittava kirjaston seurantalaite.",
    version: "Versio", whatsNew: "Mitä uutta", thirdParty: "Kolmannen osapuolen ohjelmistot",
    terms: "Käyttöehdot", privacy: "Tietosuojakäytäntö", back: "Takaisin",
    light: "Vaalea", dark: "Tumma", system: "Järjestelmä", email: "Ota meihin yhteyttä", errorLoadingBook: "Virhe ladattaessa"
  },
  sv: {
    addBook: "Lägg till bok", searchBook: "Sök efter bok...", title: "Titel", author: "Författare",
    status: "Status", toRead: "Att läsa", reading: "Läser", read: "Läst",
    save: "Spara", cancel: "Avbryt", edit: "Redigera", delete: "Radera",
    library: "Biblioteka", myLibrary: "Mitt bibliotek", noBooks: "Inga böcker hittades.",
    theme: "Tema", language: "Språk", settings: "Inställningar",
    all: "Alla", notes: "Anteckningar", coverUrl: "Omslags-URL",
    scanBarcode: "Skanna streckkod", cameraPermissionError: "Kunde inte komma åt kameran. Kontrollera behörigheter.",
    cameraError: "Ett fel uppstod vid start av kameran.", closeScanner: "Stäng skanner",
    totalBooks: "Totalt antal böcker", pagesRead: "Sidor lästa", avgRating: "Genomsnittligt betyg",
    stats: "Statistik", recentBooks: "Senaste böckerna", emptyStatsDesc: "Lägg till böcker för att se din biblioteksstatistik.",
    confirmDelete: "Är du säker på att du vill radera den här boken?", appearance: "Utseende",
    dataPrivacy: "Data och integritet", exportData: "Exportera data", importData: "Importera data",
    about: "Om", sourceCode: "Källkod", aboutText: "Integritetsvänlig bokhållare.",
    version: "Version", whatsNew: "Nyheter", thirdParty: "Tredjepartsprogram vara",
    terms: "Användarvillkor", privacy: "Integritetspolicy", back: "Tillbaka",
    light: "Ljus", dark: "Mörk", system: "System", email: "Kontakta oss", errorLoadingBook: "Fel vid laddning"
  },
  no: {
    addBook: "Legg til bok", searchBook: "Søk etter bok...", title: "Tittel", author: "Forfatter",
    status: "Status", toRead: "Skal lese", reading: "Leser", read: "Lest",
    save: "Lagre", cancel: "Avbryt", edit: "Rediger", delete: "Slett",
    library: "Biblioteka", myLibrary: "Mitt bibliotek", noBooks: "Ingen bøker funnet.",
    theme: "Tema", language: "Språk", settings: "Innstillinger",
    all: "Alle", notes: "Notater", coverUrl: "Omslags URL",
    scanBarcode: "Skann strekkode", cameraPermissionError: "Kunne ikke få tilgang til kameraet. Sjekk tillatelser.",
    cameraError: "En feil oppstod ved oppstart av kameraet.", closeScanner: "Lukk skanner",
    totalBooks: "Totalt antall bøker", pagesRead: "Sider lest", avgRating: "Gjennomsnittlig vurdering",
    stats: "Statistikk", recentBooks: "Siste bøker", emptyStatsDesc: "Legg til bøker for å se bibliotekstatistikken din.",
    confirmDelete: "Er du sikker på at du vil slette denne boken?", appearance: "Utseende",
    dataPrivacy: "Data og personvern", exportData: "Eksporter data", importData: "Importer data",
    about: "Om", sourceCode: "Kildekode", aboutText: "Personvernvennlig boksporer.",
    version: "Versjon", whatsNew: "Hva er nytt", thirdParty: "Tredjepartsprogramvare",
    terms: "Vilkår for bruk", privacy: "Personvernerklæring", back: "Tilbake",
    light: "Lys", dark: "Mørk", system: "System", email: "Kontakt oss", errorLoadingBook: "Feil ved innlasting"
  },
  da: {
    addBook: "Tilføj bog", searchBook: "Søg efter bog...", title: "Titel", author: "Forfatter",
    status: "Status", toRead: "Skal læses", reading: "Læser", read: "Læst",
    save: "Gem", cancel: "Annuller", edit: "Rediger", delete: "Slet",
    library: "Biblioteka", myLibrary: "Mit bibliotek", noBooks: "Ingen bøger fundet.",
    theme: "Tema", language: "Sprog", settings: "Indstillinger",
    all: "Alle", notes: "Noter", coverUrl: "Omslags URL",
    scanBarcode: "Scan stregkode", cameraPermissionError: "Kunne ikke få adgang til kameraet. Kontroller tilladelser.",
    cameraError: "Der opstod en fejl ved start af kameraet.", closeScanner: "Luk scanner",
    totalBooks: "Samlet antal bøger", pagesRead: "Sider læst", avgRating: "Gennemsnitlig bedømmelse",
    stats: "Statistik", recentBooks: "Seneste bøger", emptyStatsDesc: "Tilføj bøger for at se din biblioteksstatistik.",
    confirmDelete: "Er du sikker på, at du vil slette denne bog?", appearance: "Udseende",
    dataPrivacy: "Data og privatliv", exportData: "Eksporter data", importData: "Importer data",
    about: "Om", sourceCode: "Kildekode", aboutText: "Privatlivsvenlig bogsporer.",
    version: "Version", whatsNew: "Hvad er nyt", thirdParty: "Tredjepartssoftware",
    terms: "Vilkår for brug", privacy: "Privatlivspolitik", back: "Tilbage",
    light: "Lys", dark: "Mørk", system: "System", email: "Kontakt os", errorLoadingBook: "Fejl ved indlæsning"
  },
  nl: {
    addBook: "Boek toevoegen", searchBook: "Zoek boek...", title: "Titel", author: "Auteur",
    status: "Status", toRead: "Te lezen", reading: "Aan het lezen", read: "Gelezen",
    save: "Opslaan", cancel: "Annuleren", edit: "Bewerken", delete: "Verwijderen",
    library: "Biblioteka", myLibrary: "Mijn bibliotheek", noBooks: "Geen boeken gevonden.",
    theme: "Thema", language: "Taal", settings: "Instellingen",
    all: "Alle", notes: "Notities", coverUrl: "Omslag URL",
    scanBarcode: "Barcode scannen", cameraPermissionError: "Kon geen toegang krijgen tot de camera. Controleer rechten.",
    cameraError: "Er is een fout opgetreden bij het starten van de camera.", closeScanner: "Sluit scanner",
    totalBooks: "Totaal boeken", pagesRead: "Gelezen pagina's", avgRating: "Gemiddelde beoordeling",
    stats: "Statistieken", recentBooks: "Recente boeken", emptyStatsDesc: "Voeg boeken toe om je bibliotheekstatistieken te zien.",
    confirmDelete: "Weet je zeker dat je dit boek wilt verwijderen?", appearance: "Uiterlijk",
    dataPrivacy: "Gegevens & Privacy", exportData: "Data exporteren", importData: "Data importeren",
    about: "Over", sourceCode: "Broncode", aboutText: "Privacyvriendelijke boeken tracker.",
    version: "Versie", whatsNew: "Wat is nieuw", thirdParty: "Software van derden",
    terms: "Gebruiksvoorwaarden", privacy: "Privacybeleid", back: "Terug",
    light: "Licht", dark: "Donker", system: "Systeem", email: "Neem contact op", errorLoadingBook: "Fout bij laden"
  },
  lb: {
    addBook: "Buch derbäisetzen", searchBook: "Buch sichen...", title: "Titel", author: "Auteur",
    status: "Status", toRead: "Ze liesen", reading: "Am liesen", read: "Gelies",
    save: "Späicheren", cancel: "Ofbriechen", edit: "Änneren", delete: "Läschen",
    library: "Biblioteka", myLibrary: "Meng Bibliothéik", noBooks: "Keng Bicher fonnt.",
    theme: "Thema", language: "Sprooch", settings: "Astellungen",
    all: "All", notes: "Notizen", coverUrl: "Cover URL",
    scanBarcode: "Barcode scannen", cameraPermissionError: "Keen absolute Kamera. Kuckt Rechter.",
    cameraError: "Feeler beim Kamera Start.", closeScanner: "Scanner zoumaachen",
    totalBooks: "Total Bicher", pagesRead: "Säite gelies", avgRating: "Duerchschnëttlech Bewäertung",
    stats: "Statistiken", recentBooks: "Neist Bicher", emptyStatsDesc: "Füügt Bicher bäi fir är Statistiken ze gesinn.",
    confirmDelete: "Sidd dir sécher dëst Buch ze läschen?", appearance: "Ausgesinn",
    dataPrivacy: "Daten a Privatsphär", exportData: "Daten exportéieren", importData: "Daten importéieren",
    about: "Iwwer", sourceCode: "Quellcode", aboutText: "Privatsphär frëndleche Bicherscanner.",
    version: "Versioun", whatsNew: "Wat ass nei", thirdParty: "Drëtt Partei Software",
    terms: "Benotzungsbedéngungen", privacy: "Dateschutzrichtlinn", back: "Zréck",
    light: "Liicht", dark: "Däischter", system: "System", email: "Kontaktéiert eis", errorLoadingBook: "Feeler beim Lueden"
  },
  pt: {
    addBook: "Adicionar livro", searchBook: "Pesquisar livro...", title: "Título", author: "Autor",
    status: "Estado", toRead: "Para ler", reading: "A ler", read: "Lido",
    save: "Guardar", cancel: "Cancelar", edit: "Editar", delete: "Eliminar",
    library: "Biblioteka", myLibrary: "A minha biblioteca", noBooks: "Nenhum livro encontrado.",
    theme: "Tema", language: "Idioma", settings: "Definições",
    all: "Todos", notes: "Notas", coverUrl: "URL da capa",
    scanBarcode: "Digitalizar código de barras", cameraPermissionError: "Não foi possível aceder à câmara.",
    cameraError: "Ocorreu um erro ao iniciar a câmara.", closeScanner: "Fechar scanner",
    totalBooks: "Total de livros", pagesRead: "Páginas lidas", avgRating: "Avaliação média",
    stats: "Estatísticas", recentBooks: "Livros recentes", emptyStatsDesc: "Adicione livros para ver as suas estatísticas.",
    confirmDelete: "Tem a certeza que deseja eliminar este livro?", appearance: "Aparência",
    dataPrivacy: "Dados e Privacidade", exportData: "Exportar dados", importData: "Importar dados",
    about: "Sobre", sourceCode: "Código fonte", aboutText: "Rastreador de livros focado na privacidade.",
    version: "Versão", whatsNew: "Novidades", thirdParty: "Software de terceiros",
    terms: "Termos de Serviço", privacy: "Política de Privacidade", back: "Voltar",
    light: "Claro", dark: "Escuro", system: "Sistema", email: "Contacte-nos", errorLoadingBook: "Erro"
  },
  it: {
    addBook: "Aggiungi libro", searchBook: "Cerca libro...", title: "Titolo", author: "Autore",
    status: "Stato", toRead: "Da leggere", reading: "In lettura", read: "Letto",
    save: "Salva", cancel: "Annulla", edit: "Modifica", delete: "Elimina",
    library: "Biblioteka", myLibrary: "La mia libreria", noBooks: "Nessun libro trovato.",
    theme: "Tema", language: "Lingua", settings: "Impostazioni",
    all: "Tutti", notes: "Note", coverUrl: "URL copertina",
    scanBarcode: "Scansiona codice a barre", cameraPermissionError: "Impossibile accedere alla fotocamera. Controlla i permessi.",
    cameraError: "Errore all'avvio della fotocamera.", closeScanner: "Chiudi scanner",
    totalBooks: "Libri totali", pagesRead: "Pagine lette", avgRating: "Valutazione media",
    stats: "Statistiche", recentBooks: "Libri recenti", emptyStatsDesc: "Aggiungi libri per vedere le statistiche della tua libreria.",
    confirmDelete: "Sei sicuro di voler eliminare questo libro?", appearance: "Aspetto",
    dataPrivacy: "Dati e Privacy", exportData: "Esporta dati", importData: "Importa dati",
    about: "Informazioni", sourceCode: "Codice sorgente", aboutText: "Tracker di libri attento alla privacy.",
    version: "Versione", whatsNew: "Novità", thirdParty: "Software di terze parti",
    terms: "Termini e Condizioni", privacy: "Informativa sulla privacy", back: "Indietro",
    light: "Chiaro", dark: "Scuro", system: "Sistema", email: "Contattaci", errorLoadingBook: "Errore di caricamento"
  },
  hr: {
    addBook: "Dodaj knjigu", searchBook: "Pretraži knjigu...", title: "Naslov", author: "Autor",
    status: "Status", toRead: "Za čitanje", reading: "Čitam", read: "Pročitano",
    save: "Spremi", cancel: "Odustani", edit: "Uredi", delete: "Obriši",
    library: "Biblioteka", myLibrary: "Moja knjižnica", noBooks: "Nema knjiga.",
    theme: "Tema", language: "Jezik", settings: "Postavke",
    all: "Sve", notes: "Bilješke", coverUrl: "URL naslovnice",
    scanBarcode: "Skeniraj barkod", cameraPermissionError: "Pristup kameri nije moguć. Provjerite dozvole.",
    cameraError: "Greška pri pokretanju kamere.", closeScanner: "Zatvori skener",
    totalBooks: "Ukupno knjiga", pagesRead: "Pročitane stranice", avgRating: "Prosječna ocjena",
    stats: "Statistika", recentBooks: "Nedavne knjige", emptyStatsDesc: "Dodajte knjige za prikaz statistike.",
    confirmDelete: "Jeste li sigurni da želite obrisati ovu knjigu?", appearance: "Izgled",
    dataPrivacy: "Podaci i privatnost", exportData: "Izvezi podatke", importData: "Uvezi podatke",
    about: "O aplikaciji", sourceCode: "Izvorni kod", aboutText: "Aplikacija za praćenje knjiga prilagođena privatnosti.",
    version: "Verzija", whatsNew: "Što je novo", thirdParty: "Softver treće strane",
    terms: "Uvjeti korištenja", privacy: "Politika privatnosti", back: "Natrag",
    light: "Svijetla", dark: "Tamna", system: "Sistem", email: "Kontakt", errorLoadingBook: "Greška pri učitavanju"
  },
  sk: {
    addBook: "Pridať knihu", searchBook: "Hľadať knihu...", title: "Názov", author: "Autor",
    status: "Stav", toRead: "Na čítanie", reading: "Čítam", read: "Prečítané",
    save: "Uložiť", cancel: "Zrušiť", edit: "Upraviť", delete: "Vymazať",
    library: "Biblioteka", myLibrary: "Moja knižnica", noBooks: "Nenašli sa žiadne knihy.",
    theme: "Téma", language: "Jazyk", settings: "Nastavenia",
    all: "Všetky", notes: "Poznámky", coverUrl: "URL obálky",
    scanBarcode: "Skenovať čiarový kód", cameraPermissionError: "Nedá sa získať prístup ku kamere.",
    cameraError: "Chyba pri štarte kamery.", closeScanner: "Zatvoriť skener",
    totalBooks: "Celkom kníh", pagesRead: "Prečítané strany", avgRating: "Priemerné hodnotenie",
    stats: "Štatistiky", recentBooks: "Nedávne knihy", emptyStatsDesc: "Pridajte knihy a pozrite si štatistiky knižnice.",
    confirmDelete: "Naozaj chcete vymazať túto knihu?", appearance: "Vzhľad",
    dataPrivacy: "Údaje a súkromie", exportData: "Exportovať údaje", importData: "Importovať údaje",
    about: "O aplikácii", sourceCode: "Zdrojový kód", aboutText: "Aplikácia na sledovanie kníh chrániaca súkromie.",
    version: "Verzia", whatsNew: "Čo je nové", thirdParty: "Softvér tretích strán",
    terms: "Podmienky používania", privacy: "Zásady ochrany osobných údajov", back: "Späť",
    light: "Svetlý", dark: "Tmavý", system: "Systém", email: "Kontakt", errorLoadingBook: "Chyba načítania"
  },
  et: {
    addBook: "Lisa raamat", searchBook: "Otsi raamatut...", title: "Pealkiri", author: "Autor",
    status: "Olek", toRead: "Lugeda", reading: "Loen", read: "Loetud",
    save: "Salvesta", cancel: "Tühista", edit: "Muuda", delete: "Kustuta",
    library: "Biblioteka", myLibrary: "Minu raamatukogu", noBooks: "Raamatuid ei leitud.",
    theme: "Teema", language: "Keel", settings: "Seaded",
    all: "Kõik", notes: "Märkmed", coverUrl: "Kaane URL",
    scanBarcode: "Skanni triipkood", cameraPermissionError: "Kaamerale ei pääse ligi.",
    cameraError: "Kaamera käivitamisel ilmnes viga.", closeScanner: "Sulge skanner",
    totalBooks: "Kokku raamatuid", pagesRead: "Loetud lehekülgi", avgRating: "Keskmine hinne",
    stats: "Statistika", recentBooks: "Viimased raamatud", emptyStatsDesc: "Lisa raamatuid statistika nägemiseks.",
    confirmDelete: "Kas soovid kindlasti selle raamatu kustutada?", appearance: "Välimus",
    dataPrivacy: "Andmed ja privaatsus", exportData: "Ekspordi andmed", importData: "Impordi andmed",
    about: "Teave", sourceCode: "Lähtekood", aboutText: "Privaatsust austav raamatujälgija.",
    version: "Versioon", whatsNew: "Mis on uut", thirdParty: "Kolmanda osapoole tarkvara",
    terms: "Kasutustingimused", privacy: "Privaatsuspoliitika", back: "Tagasi",
    light: "Hele", dark: "Tume", system: "Süsteem", email: "Kontakt", errorLoadingBook: "Laadimisviga"
  },
  lv: {
    addBook: "Pievienot grāmatu", searchBook: "Meklēt grāmatu...", title: "Nosaukums", author: "Autors",
    status: "Statuss", toRead: "Lasīšanai", reading: "Lasu", read: "Izlasīts",
    save: "Saglabāt", cancel: "Atcelt", edit: "Rediģēt", delete: "Dzēst",
    library: "Biblioteka", myLibrary: "Mana bibliotēka", noBooks: "Grāmatas nav atrastas.",
    theme: "Tēma", language: "Valoda", settings: "Iestatījumi",
    all: "Visi", notes: "Piezīmes", coverUrl: "Vāka URL",
    scanBarcode: "Skenēt svītrkodu", cameraPermissionError: "Nevar piekļūt kamerai.",
    cameraError: "Kļūda, startējot kameru.", closeScanner: "Aizvērt skeneri",
    totalBooks: "Kopā grāmatas", pagesRead: "Izlasītas lapas", avgRating: "Vidējais vērtējums",
    stats: "Statistika", recentBooks: "Jaunākās grāmatas", emptyStatsDesc: "Pievienojiet grāmatas statistikas skatīšanai.",
    confirmDelete: "Vai tiešām vēlaties dzēst šo grāmatu?", appearance: "Izskats",
    dataPrivacy: "Dati un privātums", exportData: "Eksportēt datus", importData: "Importēt datus",
    about: "Par", sourceCode: "Pirmkods", aboutText: "Privātumu ievērojošs grāmatu izsekotājs.",
    version: "Versija", whatsNew: "Kas jauns", thirdParty: "Trešo pušu programmatūra",
    terms: "Lietošanas noteikumi", privacy: "Privātuma politika", back: "Atpakaļ",
    light: "Gaišs", dark: "Tumšs", system: "Sistēma", email: "Saziņa", errorLoadingBook: "Kļūda"
  },
  lt: {
    addBook: "Pridėti knygą", searchBook: "Ieškoti knygos...", title: "Pavadinimas", author: "Autorius",
    status: "Būsena", toRead: "Skaityti", reading: "Skaitoma", read: "Perskaityta",
    save: "Išsaugoti", cancel: "Atšaukti", edit: "Redaguoti", delete: "Ištrinti",
    library: "Biblioteka", myLibrary: "Mano biblioteka", noBooks: "Knygų nerasta.",
    theme: "Tema", language: "Kalba", settings: "Nustatymai",
    all: "Visi", notes: "Užrašai", coverUrl: "Viršelio URL",
    scanBarcode: "Skenuoti brūkšninį kodą", cameraPermissionError: "Nepavyko pasiekti kameros.",
    cameraError: "Klaida paleidžiant kamerą.", closeScanner: "Uždaryti skenerį",
    totalBooks: "Iš viso knygų", pagesRead: "Perskaityta puslapių", avgRating: "Vidutinis įvertinimas",
    stats: "Statistika", recentBooks: "Naujausios knygos", emptyStatsDesc: "Pridėkite knygų statistikai matyti.",
    confirmDelete: "Ar tikrai norite ištrinti šią knygą?", appearance: "Išvaizda",
    dataPrivacy: "Duomenys ir privatumas", exportData: "Eksportuoti duomenis", importData: "Importuoti duomenis",
    about: "Apie", sourceCode: "Šaltinio kodas", aboutText: "Privatumą vertinantis knygų sekiklis.",
    version: "Versija", whatsNew: "Kas naujo", thirdParty: "Trečiųjų šalių programinė įranga",
    terms: "Naudojimo sąlygos", privacy: "Privatumo politika", back: "Atgal",
    light: "Šviesi", dark: "Tamsi", system: "Sistema", email: "Susisiekite", errorLoadingBook: "Klaida"
  },
  bg: {
    addBook: "Добавете книга", searchBook: "Търсене на книга...", title: "Заглавие", author: "Автор",
    status: "Статус", toRead: "За четене", reading: "Чета", read: "Прочетена",
    save: "Запазване", cancel: "Отказ", edit: "Редактиране", delete: "Изтриване",
    library: "Biblioteka", myLibrary: "Моята библиотека", noBooks: "Няма намерени книги.",
    theme: "Тема", language: "Език", settings: "Настройки",
    all: "Всички", notes: "Бележки", coverUrl: "URL на корицата",
    scanBarcode: "Сканиране на баркод", cameraPermissionError: "Няма достъп до камерата.",
    cameraError: "Грешка при зареждане на камерата.", closeScanner: "Затвори скенера",
    totalBooks: "Общо книги", pagesRead: "Прочетени страници", avgRating: "Средна оценка",
    stats: "Статистика", recentBooks: "Последни книги", emptyStatsDesc: "Добавете книги за статистика.",
    confirmDelete: "Сигурни ли сте, че искате да изтриете книгата?", appearance: "Външен вид",
    dataPrivacy: "Данни и поверителност", exportData: "Експорт на данни", importData: "Импорт на данни",
    about: "За нас", sourceCode: "Изходен код", aboutText: "Тракер за книги, уважаващ поверителността.",
    version: "Версия", whatsNew: "Какво ново", thirdParty: "Софтуер на трети страни",
    terms: "Условия", privacy: "Политика за поверителност", back: "Назад",
    light: "Светла", dark: "Тъмна", system: "Система", email: "Контакт", errorLoadingBook: "Грешка"
  },
  tr: {
    addBook: "Kitap Ekle", searchBook: "Kitap Ara...", title: "Başlık", author: "Yazar",
    status: "Durum", toRead: "Okunacak", reading: "Okunuyor", read: "Okundu",
    save: "Kaydet", cancel: "İptal", edit: "Düzenle", delete: "Sil",
    library: "Biblioteka", myLibrary: "Kütüphanem", noBooks: "Kitap bulunamadı.",
    theme: "Tema", language: "Dil", settings: "Ayarlar",
    all: "Tümü", notes: "Notlar", coverUrl: "Kapak URL",
    scanBarcode: "Barkod Tara", cameraPermissionError: "Kameraya erişim sağlanamadı.",
    cameraError: "Kamerayı başlatırken bir hata oluştu.", closeScanner: "Tarayıcıyı Kapat",
    totalBooks: "Toplam Kitap", pagesRead: "Okunan Sayfa", avgRating: "Ortalama Puan",
    stats: "İstatistikler", recentBooks: "Son Kitaplar", emptyStatsDesc: "İstatistikleri görmek için kitap ekleyin.",
    confirmDelete: "Bu kitabı silmek istediğinize emin misiniz?", appearance: "Görünüm",
    dataPrivacy: "Veri ve Gizlilik", exportData: "Verileri Dışa Aktar", importData: "Verileri İçe Aktar",
    about: "Hakkında", sourceCode: "Kaynak Kod", aboutText: "Gizlilik dostu kitap izleyici.",
    version: "Sürüm", whatsNew: "Yenilikler", thirdParty: "Üçüncü Taraf Yazılımları",
    terms: "Kullanım Koşulları", privacy: "Gizlilik Politikası", back: "Geri",
    light: "Açık", dark: "Koyu", system: "Sistem", email: "İletişim", errorLoadingBook: "Hata"
  },
  ko: {
    addBook: "책 추가", searchBook: "책 검색...", title: "제목", author: "저자",
    status: "상태", toRead: "읽을 책", reading: "읽는 중", read: "읽음",
    save: "저장", cancel: "취소", edit: "편집", delete: "삭제",
    library: "Biblioteka", myLibrary: "내 서재", noBooks: "책을 찾을 수 없습니다.",
    theme: "테마", language: "언어", settings: "설정",
    all: "모두", notes: "메모", coverUrl: "표지 URL",
    scanBarcode: "바코드 스캔", cameraPermissionError: "카메라에 접근할 수 없습니다.",
    cameraError: "카메라를 시작하는 중 오류가 발생했습니다.", closeScanner: "스캐너 닫기",
    totalBooks: "총 책 수", pagesRead: "읽은 페이지 수", avgRating: "평균 평점",
    stats: "통계", recentBooks: "최근 읽은 책", emptyStatsDesc: "통계를 보려면 책을 추가하세요.",
    confirmDelete: "이 책을 삭제하시겠습니까?", appearance: "모양",
    dataPrivacy: "데이터 및 개인 정보", exportData: "데이터 내보내기", importData: "데이터 가져오기",
    about: "정보", sourceCode: "소스 코드", aboutText: "프라이버시를 존중하는 도서 트래커.",
    version: "버전", whatsNew: "새로운 기능", thirdParty: "타사 소프트웨어",
    terms: "이용 약관", privacy: "개인 정보 정책", back: "뒤로",
    light: "라이트", dark: "다크", system: "시스템", email: "문의하기", errorLoadingBook: "오류"
  },
  ja: {
    addBook: "本を追加", searchBook: "本を検索...", title: "タイトル", author: "著者",
    status: "ステータス", toRead: "読みたい", reading: "読書中", read: "読んだ",
    save: "保存", cancel: "キャンセル", edit: "編集", delete: "削除",
    library: "Biblioteka", myLibrary: "マイライブラリ", noBooks: "本が見つかりません。",
    theme: "テーマ", language: "言語", settings: "設定",
    all: "すべて", notes: "メモ", coverUrl: "表紙URL",
    scanBarcode: "バーコードをスキャン", cameraPermissionError: "カメラにアクセスできませんでした。",
    cameraError: "カメラの起動中にエラーが発生しました。", closeScanner: "スキャナーを閉じる",
    totalBooks: "総書籍数", pagesRead: "読んだページ数", avgRating: "平均評価",
    stats: "統計", recentBooks: "最近の本", emptyStatsDesc: "統計を見るには本を追加してください。",
    confirmDelete: "この本を削除してもよろしいですか？", appearance: "外観",
    dataPrivacy: "データとプライバシー", exportData: "データのエクスポート", importData: "データのインポート",
    about: "概要", sourceCode: "ソースコード", aboutText: "プライバシー重視の読書トラッカー。",
    version: "バージョン", whatsNew: "新着情報", thirdParty: "サードパーティソフトウェア",
    terms: "利用規約", privacy: "プライバシーポリシー", back: "戻る",
    light: "ライト", dark: "ダーク", system: "システム", email: "お問い合わせ", errorLoadingBook: "エラー"
  },
  is: {
    addBook: "Bæta við bók", searchBook: "Leita að bók...", title: "Titill", author: "Höfundur",
    status: "Staða", toRead: "Til að lesa", reading: "Er að lesa", read: "Lesin",
    save: "Vista", cancel: "Hætta við", edit: "Breyta", delete: "Eyða",
    library: "Biblioteka", myLibrary: "Bókasafnið mitt", noBooks: "Engar bækur fundust.",
    theme: "Þema", language: "Tungumál", settings: "Stillingar",
    all: "Allar", notes: "Glósur", coverUrl: "Slóð á forsíðu",
    scanBarcode: "Skanna strikamerki", cameraPermissionError: "Hefur ekki aðgang að myndavélinni.",
    cameraError: "Villa við að ræsa myndavélina.", closeScanner: "Loka skanna",
    totalBooks: "Samtals bækur", pagesRead: "Lesnar síður", avgRating: "Meðaleinkunn",
    stats: "Tölfræði", recentBooks: "Nýlegar bækur", emptyStatsDesc: "Bættu við bókum til að sjá tölfræði bókasafnsins þíns.",
    confirmDelete: "Ertu viss um að þú viljir eyða þessari bók?", appearance: "Útlit",
    dataPrivacy: "Gögn og persónuvernd", exportData: "Flytja út gögn", importData: "Flytja inn gögn",
    about: "Um", sourceCode: "Kóði", aboutText: "Persónuverndarvænn bókasafnsmælir.",
    version: "Útgáfa", whatsNew: "Hvað er nýtt", thirdParty: "Hugbúnaður frá þriðja aðila",
    terms: "Notkunarskilmálar", privacy: "Persónuverndarstefna", back: "Til baka",
    light: "Ljóst", dark: "Dökkt", system: "Kerfi", email: "Hafa samband", errorLoadingBook: "Villa"
  },
  kl: {
    addBook: "Atuakkamik ilanngussigit", searchBook: "Atuagaq ujaruk...", title: "Qulequtaq", author: "Allattoq",
    status: "Inissisimaffik", toRead: "Atuarneqassaaq", reading: "Atuarpara", read: "Atuareerpara",
    save: "Toqqoruk", cancel: "Silaq", edit: "Aaqqissuuguk", delete: "Peeriuk",
    library: "Biblioteka", myLibrary: "Atuakkanik toqqorsiviga", noBooks: "Atuakkanik nassaassanngilaq.",
    theme: "Qanoq iluseq", language: "Oqaatsit", settings: "Aaqqissuussinerit",
    all: "Tamarmik", notes: "Allattukkat", coverUrl: "Saqqaa URL",
    scanBarcode: "Stregekode scanneriut", cameraPermissionError: "Kamera atorsinnaanngilaq.",
    cameraError: "Kamera aallartinnerani kukkusoqarpoq.", closeScanner: "Scanneri matuuk",
    totalBooks: "Atuakkat katillugit", pagesRead: "Quppernerit atuarneqartut", avgRating: "Agguaqatigiissillugu tatigassuseq",
    stats: "Kisitsisitigut nassuiaatit", recentBooks: "Atuakkat kingulliit", emptyStatsDesc: "Atuakkat ilanngugit kisitsisit takuniarlugit.",
    confirmDelete: "Atuagaq una peerniarpiuk?", appearance: "Takusinnaasaq",
    dataPrivacy: "Paasissutissat isertuussassat", exportData: "Paasissutissat annigutik", importData: "Paasissutissat eqquguk",
    about: "Pillugu", sourceCode: "Kode toqqammaviliaq", aboutText: "Atuakkanut takussutissiat isertuussassanik ataqqinnittut.",
    version: "Pissusaa", whatsNew: "Nutaaq", thirdParty: "Programmit allat",
    terms: "Atuinermut piumasaqaatit", privacy: "Paasissutissat isertuussat", back: "Uteqqit",
    light: "Qaamasoq", dark: "Taartumik", system: "Aaqqissuussivik", email: "Attavigiigut", errorLoadingBook: "Kukkuneq"
  }
};

let lines = i18nContent.split('\n');

const lastBracket = lines.lastIndexOf('};');
if (lastBracket !== -1) {
    let str = '';
    for (const [lang, translationsObj] of Object.entries(translations)) {
        str += `\n  ${lang}: {`;
        for (const [key, value] of Object.entries(translationsObj)) {
            str += `\n    ${key}: ${JSON.stringify(value)},`;
        }
        str += `\n  },`;
    }
    lines.splice(lastBracket, 0, str);
}

fs.writeFileSync(i18nPath, lines.join('\n'));
